/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Mon Apr 30 16:46:57 2018. */

#include "mytest.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AllValue_fields[17] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, AllValue, myfloat, myfloat, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, AllValue, myint32, myfloat, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, AllValue, myint64, myint32, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, AllValue, myuint32, myint64, 0),
    PB_FIELD(  5, UINT64  , REQUIRED, STATIC  , OTHER, AllValue, myuint64, myuint32, 0),
    PB_FIELD(  6, SINT32  , REQUIRED, STATIC  , OTHER, AllValue, mysint32, myuint64, 0),
    PB_FIELD(  7, SINT64  , REQUIRED, STATIC  , OTHER, AllValue, mysin64, mysint32, 0),
    PB_FIELD(  8, FIXED32 , REQUIRED, STATIC  , OTHER, AllValue, myfixed32, mysin64, 0),
    PB_FIELD(  9, FIXED64 , REQUIRED, STATIC  , OTHER, AllValue, myfixed64, myfixed32, 0),
    PB_FIELD( 10, SFIXED32, REQUIRED, STATIC  , OTHER, AllValue, mysfixed32, myfixed64, 0),
    PB_FIELD( 11, SFIXED64, REQUIRED, STATIC  , OTHER, AllValue, mysfinxed64, mysfixed32, 0),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, AllValue, mybool, mysfinxed64, 0),
    PB_FIELD( 13, STRING  , REQUIRED, CALLBACK, OTHER, AllValue, mystring, mybool, 0),
    PB_FIELD( 14, BYTES   , REQUIRED, CALLBACK, OTHER, AllValue, mybytes, mystring, 0),
    PB_FIELD( 15, UINT32  , OPTIONAL, STATIC  , OTHER, AllValue, myAge, mybytes, 0),
    PB_FIELD( 16, UINT32  , REPEATED, CALLBACK, OTHER, AllValue, myList, myAge, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
