/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Mon Apr 30 16:46:57 2018. */

#ifndef PB_MYTEST_PB_H_INCLUDED
#define PB_MYTEST_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AllValue {
    float myfloat;
    int32_t myint32;
    int64_t myint64;
    uint32_t myuint32;
    uint64_t myuint64;
    int32_t mysint32;
    int64_t mysin64;
    uint32_t myfixed32;
    uint64_t myfixed64;
    int32_t mysfixed32;
    int64_t mysfinxed64;
    bool mybool;
    pb_callback_t mystring;
    pb_callback_t mybytes;
    bool has_myAge;
    uint32_t myAge;
    pb_callback_t myList;
/* @@protoc_insertion_point(struct:AllValue) */
} AllValue;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AllValue_init_default                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define AllValue_init_zero                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define AllValue_myfloat_tag                     1
#define AllValue_myint32_tag                     2
#define AllValue_myint64_tag                     3
#define AllValue_myuint32_tag                    4
#define AllValue_myuint64_tag                    5
#define AllValue_mysint32_tag                    6
#define AllValue_mysin64_tag                     7
#define AllValue_myfixed32_tag                   8
#define AllValue_myfixed64_tag                   9
#define AllValue_mysfixed32_tag                  10
#define AllValue_mysfinxed64_tag                 11
#define AllValue_mybool_tag                      12
#define AllValue_mystring_tag                    13
#define AllValue_mybytes_tag                     14
#define AllValue_myAge_tag                       15
#define AllValue_myList_tag                      16

/* Struct field encoding specification for nanopb */
extern const pb_field_t AllValue_fields[17];

/* Maximum encoded size of messages (where known) */
/* AllValue_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MYTEST_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
